import unittest, importlib.util
from pathlib import Path
P=Path(__file__).parents[1]/"engine"/"procurement_evidence_recovery.py"
spec=importlib.util.spec_from_file_location("c7",P); m=importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
class T(unittest.TestCase):
 def test_01(self): self.assertEqual(m.pack_acquisition_gate(True,False),"BLOCKED_AUTHENTICATED_DOCUMENT_SURFACE")
 def test_02(self): self.assertEqual(m.pack_acquisition_gate(True,True),"PACK_ACQUIRED")
 def test_03(self): self.assertEqual(m.supplier_packet_gate(False),"HOLD_NO_VERIFIED_SUPPLIER_PACKET")
 def test_04(self): self.assertEqual(m.requirement_join_gate(False,True),"BLOCKED_INCOMPLETE_EVIDENCE")
 def test_05(self): self.assertEqual(m.requirement_join_gate(True,True),"JOIN_ALLOWED")
 def test_06(self): self.assertEqual(m.classify_gap(True,True,True),"MET")
 def test_07(self): self.assertEqual(m.classify_gap(True,True,False,None),"UNKNOWN")
 def test_08(self): self.assertEqual(m.classify_gap(True,True,False,True),"CURABLE_BEFORE_DEADLINE")
 def test_09(self): self.assertEqual(m.classify_gap(True,True,False,False),"NONCURABLE")
 def test_10(self): self.assertEqual(m.classify_gap(True,False,False),"NOT_APPLICABLE")
 def test_11(self): self.assertEqual(m.meat_gate(False,False),"PARTIAL_MEAT")
 def test_12(self): self.assertEqual(m.site_constraint_gate(False),"PARTIAL_PUBLIC_SCOPE")
 def test_13(self): self.assertEqual(m.finance_gate(True,False),"PARTIAL_PUBLIC_FINANCE")
 def test_14(self): self.assertEqual(m.pa4_gate(False,False,True,True,True),"BLOCKED_PA4_PACKET_INCOMPLETE")
 def test_15(self): self.assertEqual(m.pa4_gate(True,True,False,True,True),"BLOCKED_PA4_INDEPENDENCE")
 def test_16(self): self.assertEqual(m.real_user_gate(True,False,True),"HOLD_NO_OUTREACH")
 def test_17(self): self.assertEqual(m.substitute_residual(True,True,True),"RESIDUAL_QUALIFICATION_EVIDENCE_READINESS")
 def test_18(self): self.assertEqual(m.field_refresh_gate(False,False,True),"REVALIDATE")
 def test_19(self): self.assertEqual(m.false_confidence_guard(True,False,False),"REJECT_CONFIDENCE_PROMOTION")
 def test_20(self): self.assertEqual(m.wip_gate(1,2),"PASS_WIP")
 def test_21(self): self.assertEqual(m.si_candidate_gate(1,True),"HOLD_CANDIDATE_ONLY")
 def test_22(self): self.assertEqual(m.pa5_gate(False,False,False),"PA5_FALSE")
 def test_23(self): self.assertEqual(m.e3_gate(False,False),"E3_FALSE"); self.assertEqual(m.e4_gate(0,True,True),"E4_FALSE")
 def test_24(self): self.assertEqual(m.cycle_close_gate(True,True,True,False,True),"HOLD_PERSISTENCE"); self.assertIsNone(m.null_safe_number(0,False))
if __name__=="__main__": unittest.main()
