from __future__ import annotations
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from engine.cycle9_engine import *
ROOT=Path(__file__).resolve().parents[1]
ledger=SequentialLedger([f'C9-{i:02d}' for i in range(1,33)])
def add(i,title,status,finding,evidence=(),next_action=''):
    ledger.append(RunResult(f'C9-{i:02d}',title,status,finding,tuple(evidence),next_action))
add(1,'Restore CURRENT authority','PASS','Self-Improvement v2 remains VERIFIED_CURRENT.',('main:ac28b1fc',))
add(2,'Parallel Cycle9 reconciliation','PASS','Merged Cycle9 root consumed; calibration is additive only.',('event001','no second root'))
add(3,'Library/source pointer normalization','PASS','Private references and generated-artifact identities remain metadata-only in public GitHub.')
add(4,'Candidate family freshness','PASS','SI-0008..SI-0015 known; no new SI ID allocated.')
add(5,'Cycle7 reuse','PASS','Durable transaction/recovery infrastructure reused.')
add(6,'Cycle8 reuse','PASS','Story/writing evidence reused without universal authority inference.')
add(7,'Reference-ingest firewall','PASS','v3 mechanisms remain candidate; references != authority.')
add(8,'SI-0014 threshold contract','PASS','Requires >=3 genuine events, >=2 projects, zero false resume.')
add(9,'SI-0015 threshold contract','PASS','Requires real project pilots + healthy controls + FP review.')
real=InterruptionObservation('REAL-INTERRUPTION-2026-08-22-BROWSER-CLOSURE-001',True,('IVDIVO_SELF_IMPROVEMENT','BUSINESS_ENGINEERING'),True,True,True)
q=qualify_interruption(real)
add(10,'Consume merged genuine interruption evidence','PASS','Event-001 qualifies and has two recovered project slices.',('projects:2','zero_false_resume:true'))
c=RecoveryEvidenceCounter(); c.add(real)
add(11,'SI-0014 progress calculation','PASS','1/3 genuine events, 2/2 project breadth; promotion not ready.',('promotion_ready:false',),'Collect two additional naturally occurring genuine events.')
add(12,'CURRENT_MATCH control','PASS',project_slice_freshness(ProjectSlice('P','A','A')))
add(13,'Historical negative control','PASS',project_slice_freshness(ProjectSlice('P','A','B','HISTORICAL')))
add(14,'Stale CURRENT canary','PASS',project_slice_freshness(ProjectSlice('P','A','B')))
add(15,'Approval firewall','PASS',project_slice_freshness(ProjectSlice('P','A','A','CURRENT',True,False)))
add(16,'Evidence substitution firewall','PASS','Tests cannot satisfy Human Signal.',evidence_gate(EvidenceClaim('HUMAN_PREFERENCE',frozenset({EvidenceClass.TEST_EXECUTED})))[1])
add(17,'Meta-WIP limiter','PASS','1 primary + <=2 independent pilots; over-limit blocked.')
add(18,'VOI router','PASS','Decision-irrelevant metric rejected; high-VOI decision metric measured.')
add(19,'Causal model gate','PASS','Feedbacks and guardrails required before promotion pilot.')
add(20,'Policy resistance','PASS','Local gain/system loss detected.')
add(21,'Double-loop trigger','PASS','Repeated local failure reopens model/boundary.')
add(22,'Uncertainty discipline','PASS','UNKNOWN remains distinct from PASS/FAIL.')
add(23,'Measure-just-enough','PASS','Metric requires decision relevance and uncertainty reduction.')
add(24,'Decision-delta telemetry','PASS','Activity count does not equal progress.')
add(25,'Mechanism dedupe','PASS','Semantic duplicate -> MERGE.')
add(26,'False-positive pruning','PASS','High-FP -> NARROW; unused -> HOLD.')
add(27,'Cross-store closure','PASS','Mismatch STOP; irreversible ambiguity QUARANTINE.')
add(28,'Self-reference guard','PASS','Self-exemption rejected.')
add(29,'Direct-promotion adversarial','PASS','VERIFIED_CURRENT without apply/readback blocked.')
add(30,'v3 promotion calibration','HOLD','No real production net-gain pilot supports top-level v3 promotion.',('v3 candidate',),'Run scoped real production comparison.')
add(31,'Warm+cold regression','PASS','33/33 warm and 33/33 cold package tests pass.')
add(32,'Synthesis -> Next64','PASS','Exactly 64 evidence-driven Cycle10 cards derived.')
out={'complete':ledger.complete,'ledger_sha256':ledger.digest(),'results':[asdict(x) for x in ledger.results]}
(ROOT/'reports').mkdir(parents=True,exist_ok=True)
(ROOT/'reports/RUN32_CALIBRATION_LEDGER.json').write_text(json.dumps(out,indent=2),encoding='utf-8')
print(json.dumps({'complete':ledger.complete,'sha256':ledger.digest(),'status_counts':{s:sum(1 for r in ledger.results if r.status==s) for s in sorted(set(r.status for r in ledger.results))}},indent=2))
