import unittest
import wave5_convergence_core as c

class Wave5Tests(unittest.TestCase):
    def test_01_authority_rank(self): self.assertGreater(c.authority_rank("CURRENT_MAIN_AUTHORITY"),c.authority_rank("STACKED_DRAFT_PR"))
    def test_02_choose_authority(self): self.assertEqual(c.choose_authority([{"kind":"STACKED_DRAFT_PR","freshness":9},{"kind":"CURRENT_MAIN_AUTHORITY","freshness":1}])["kind"],"CURRENT_MAIN_AUTHORITY")
    def test_03_freshness_stacked(self): self.assertIn(("84","STACKED_OPEN"),c.freshness_graph([{"id":"84","state":"OPEN","base":"wave3","behind_main":0,"mergeable":True}])["risks"])
    def test_04_freshness_stale(self): self.assertIn(("86","STALE_BASE"),c.freshness_graph([{"id":"86","state":"OPEN","base":"main","behind_main":3,"mergeable":True}])["risks"])
    def test_05_freshness_merge_recheck(self): self.assertIn(("86","MERGE_FRESHNESS_RECHECK"),c.freshness_graph([{"id":"86","state":"OPEN","base":"main","behind_main":0,"mergeable":False}])["risks"])
    def test_06_dedupe_main_wins(self):
        r=c.dedupe_mechanisms([{"mechanism":"spend ledger","kind":"MAIN_BASED_DRAFT_PR","freshness":2,"evidence":2},{"mechanism":"spend-ledger","kind":"CURRENT_MAIN_AUTHORITY","freshness":1,"evidence":1}]);self.assertEqual(r["spend_ledger"]["canonical"]["kind"],"CURRENT_MAIN_AUTHORITY")
    def test_07_classify_portable(self): self.assertEqual(c.classify_delta({"class":"QC_GATE"}),"PORTABLE_MECHANISM")
    def test_08_classify_project(self): self.assertEqual(c.classify_delta({"class":"VOICE_ID"}),"PROJECT_SPECIFIC_DO_NOT_TRANSFER")
    def test_09_classify_duplicate(self): self.assertEqual(c.classify_delta({"class":"QC_GATE","duplicate":True}),"DUPLICATE")
    def test_10_manifest_no_new_runtime(self): self.assertFalse(c.convergence_manifest([{"class":"MECHANISM"}])["new_runtime_allowed"])
    def test_11_fingerprint_pass(self):
        x={"authority_revision":"r","source_sha256":"s","occurrence_ledger_sha256":"o","request_sha256":"q"};self.assertEqual(c.source_fingerprint_gate(x,x)["status"],"PASS")
    def test_12_fingerprint_missing(self): self.assertEqual(c.source_fingerprint_gate({}, {})["status"],"FAIL_CLOSED")
    def test_13_fingerprint_mismatch(self):
        g={"authority_revision":"r","source_sha256":"x","occurrence_ledger_sha256":"o","request_sha256":"q"};e={**g,"source_sha256":"s"};self.assertIn("source_sha256",c.source_fingerprint_gate(g,e)["mismatched"])
    def test_14_no_branch_fallback(self): self.assertEqual(c.no_branch_fallback(True,True,True),"BLOCK_DISPATCH")
    def test_15_preflight_only(self): self.assertEqual(c.no_branch_fallback(True,True,False),"ALLOW_PREFLIGHT_ONLY")
    def test_16_alias_pass(self): self.assertEqual(c.master_asset_alias_gate("h","h",False)["status"],"PASS_ALIAS_REUSE")
    def test_17_alias_rerender_forbidden(self): self.assertEqual(c.master_asset_alias_gate("h","h",True)["status"],"FAIL_RERENDER_FORBIDDEN")
    def test_18_alias_drift(self): self.assertEqual(c.master_asset_alias_gate("h","x",False)["status"],"FAIL_REPLAY_DRIFT")
    def test_19_replay_drift_fields(self):
        m={"audio_sha256":"a","source_hash":"s","voice_binding":"v","model":"m","post_chain":"p"};self.assertEqual(c.replay_drift(m,{**m,"model":"x"}),["model"])
    def test_20_one_listen_pass(self): self.assertEqual(c.one_listen_fact_gate(["A","B"],[])["status"],"PASS")
    def test_21_one_listen_mask(self): self.assertEqual(c.one_listen_fact_gate(["A"],["A"])["status"],"FAIL_INFORMATION_PRIORITY")
    def test_22_leakage_pass(self): self.assertEqual(c.project_leakage_gate({"x":"generic"},["Greyhaven"])["status"],"PASS")
    def test_23_leakage_fail(self): self.assertEqual(c.project_leakage_gate({"x":"Greyhaven"},["Greyhaven"])["status"],"FAIL_PROJECT_LEAKAGE")
    def test_24_clean_first_pass(self): self.assertEqual(c.clean_first_gate([],["PHONE_EQ"])["status"],"PASS")
    def test_25_clean_first_fail(self): self.assertEqual(c.clean_first_gate(["music"],[])["status"],"FAIL_BAKED_PROCESSING")
    def test_26_route_isolated_clue(self): self.assertEqual(c.route_render_block(speakers=2,chars=500,clue_identity=True)["route"],"ISOLATED_TTS")
    def test_27_route_ttd(self): self.assertEqual(c.route_render_block(speakers=2,chars=1700,clue_identity=False)["route"],"TTD_BLOCK")
    def test_28_route_split(self): self.assertEqual(c.route_render_block(speakers=2,chars=1801,clue_identity=False)["route"],"SPLIT_TTD")
    def test_29_canary_pass(self): self.assertEqual(c.canary_identity_gate(3,36,2163)["status"],"PASS")
    def test_30_canary_fail(self): self.assertEqual(c.canary_identity_gate(4,36,2163)["status"],"FAIL_CANARY_DRIFT")
    def test_31_spend_reuse(self): self.assertEqual(c.spend_decision("ACCEPTED"),"REUSE_ACCEPTED")
    def test_32_spend_ambiguous(self): self.assertEqual(c.spend_decision("AMBIGUOUS"),"RECONCILE_REQUIRED")
    def test_33_spend_response_started(self): self.assertEqual(c.spend_decision("SENT",True),"QUARANTINE_AMBIGUOUS")
    def test_34_error_voice(self): self.assertEqual(c.normalize_provider_error(400,"voice_missing")["category"],"VOICE")
    def test_35_error_rate(self): self.assertTrue(c.normalize_provider_error(429,"")["retryable"])
    def test_36_capability_pass(self): self.assertEqual(c.capability_snapshot_gate({"voice_ids":["v"],"model_ids":["m"]},{"voice_ids":["v"],"model_ids":["m"]})["status"],"PASS")
    def test_37_capability_no_swap(self): self.assertFalse(c.capability_snapshot_gate({"voice_ids":["v"],"model_ids":[]},{"voice_ids":[],"model_ids":[]})["auto_substitution"])
    def test_38_alignment_pass(self): self.assertEqual(c.alignment_coverage_gate(["U1","U2"],[{"unit_id":"U1","start":0,"end":1},{"unit_id":"U2","start":1,"end":2}])["status"],"PASS")
    def test_39_alignment_duplicate(self): self.assertEqual(c.alignment_coverage_gate(["U1","U2"],[{"unit_id":"U1","start":0,"end":1},{"unit_id":"U1","start":1,"end":2}])["status"],"FAIL_ALIGNMENT_COVERAGE")
    def test_40_alignment_synthetic(self): self.assertEqual(c.alignment_coverage_gate([],[],True)["status"],"FAIL_SYNTHETIC_TIMING")
    def test_41_passport_pass(self): self.assertEqual(c.acoustic_passport_gate({"domain_id":"A","space_type":"OUT","foreground_priority":"DIALOGUE","ambience_policy":"CAUSAL","silence_policy":"PROTECTED","project_id":"P"})["status"],"PASS")
    def test_42_passport_missing(self): self.assertEqual(c.acoustic_passport_gate({})["status"],"FAIL_PASSPORT")
    def test_43_foley_pass(self): self.assertEqual(c.causal_foley_gate({"physical_cause":"hand","action":"press","sound":"click","listener_function":"confirm"})["status"],"PASS")
    def test_44_foley_decorative(self): self.assertEqual(c.causal_foley_gate({"sound":"boom"})["status"],"FAIL_DECORATIVE_OR_UNCAUSED")
    def test_45_silence_pass(self): self.assertEqual(c.protected_silence_gate({"start":1,"end":2},[{"id":"a","kind":"DIALOGUE","start":1.1,"end":1.2}])["status"],"PASS")
    def test_46_silence_tail_fail(self): self.assertEqual(c.protected_silence_gate({"start":1,"end":2},[{"id":"r","kind":"REVERB_TAIL","start":.9,"end":1.1}])["status"],"FAIL_SILENCE_MASK")
    def test_47_stereo_mono_fail(self): self.assertEqual(c.stem_topology_gate(2,1,False),"FAIL_UNEXPECTED_STEREO_TO_MONO")
    def test_48_stereo_mono_intended(self): self.assertEqual(c.stem_topology_gate(2,1,True),"PASS")
    def test_49_media_pass(self): self.assertEqual(c.media_state_gate("W","W",True,False),"PASS")
    def test_50_media_world_fail(self): self.assertEqual(c.media_state_gate("A","B",True,False),"FAIL_WORLD_IDENTITY")
    def test_51_music_hold_last(self): self.assertEqual(c.music_function_gate(dialogue_space_pass=False,human_gain=False,overlaps_protected_silence=False,masks_fact=False,premature_answer=False),"HOLD_GENERATE_LAST")
    def test_52_music_reject_no_gain(self): self.assertEqual(c.music_function_gate(dialogue_space_pass=True,human_gain=False,overlaps_protected_silence=False,masks_fact=False,premature_answer=False),"REJECT_NO_FUNCTIONAL_GAIN")
    def test_53_music_pass(self): self.assertEqual(c.music_function_gate(dialogue_space_pass=True,human_gain=True,overlaps_protected_silence=False,masks_fact=False,premature_answer=False),"PASS_OPTIONAL")
    def test_54_info_priority_fail(self): self.assertEqual(c.information_priority_gate([{"id":"F","masked":True}])["status"],"FAIL_INFORMATION_LOSS")
    def test_55_cause_route(self): self.assertEqual(c.earliest_cause_route("stereo_collapse"),"STEM_RENDER_ROUTING")
    def test_56_repair_selective(self):
        r=c.selective_repair_plan("ALIGNMENT_TIMELINE");self.assertFalse(r["full_chapter_rerender_default"]);self.assertIn("DEPENDENT_CUES",r["invalidate"])
    def test_57_abc_set_fail(self): self.assertEqual(c.abc_benchmark_gate([{"mode":"NARRATED"}])["status"],"FAIL_VARIANT_SET")
    def test_58_abc_hold_human(self): self.assertEqual(c.abc_benchmark_gate([{"mode":m,"source_hash":"h","loudness_matched":True,"human_score":None} for m in ("NARRATED","MULTI_VOICE","DRAMATIZED")])["status"],"HOLD_HUMAN")
    def test_59_abc_pass(self): self.assertEqual(c.abc_benchmark_gate([{"mode":m,"source_hash":"h","loudness_matched":True,"human_score":4} for m in ("NARRATED","MULTI_VOICE","DRAMATIZED")])["status"],"PASS")
    def test_60_performance_hold(self): self.assertEqual(c.performance_human_gate({"multi_state":1,"pronunciation":1,"fatigue":0,"human_blind":1,"pair":1})["status"],"HOLD")
    def test_61_performance_pass(self): self.assertEqual(c.performance_human_gate({"multi_state":1,"pronunciation":1,"fatigue":1,"human_blind":1,"pair":1})["status"],"PASS")
    def test_62_economics_hold(self): self.assertEqual(c.economics_gate({})["status"],"HOLD_MEASURED")
    def test_63_economics_pass(self): self.assertEqual(c.economics_gate({"provider_cost_actual":3,"accepted_minutes_actual":2,"human_minutes_actual":10})["provider_cost_per_accepted_minute"],1.5)
    def test_64_antibloat_stop(self): self.assertEqual(c.anti_bloat_gate([{"id":"x"}])["status"],"STOP_NO_INFORMATION_GAIN")
    def test_65_antibloat_action(self): self.assertEqual(c.anti_bloat_gate([{"id":"x","unblocks_dependency":True}])["status"],"PASS")
    def test_66_release_hold(self):
        r=c.release_matrix({"canonical_runtime":"PASS","source_integrity":"PASS"});self.assertEqual(r["status"],"HOLD");self.assertFalse(r["test_count_is_quality_proof"])
    def test_67_release_go(self): self.assertEqual(c.release_matrix({k:"PASS" for k in ["canonical_runtime","source_integrity","provider_live","alignment_live","human_performance","economics_measured","portability_live"]})["status"],"GO")
    def test_68_unknown_cause_diagnose(self): self.assertEqual(c.earliest_cause_route("weird"),"DIAGNOSE_BEFORE_REPAIR")

if __name__=="__main__": unittest.main(verbosity=2)
