#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
from datetime import date

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--out",required=True); args=ap.parse_args()
    signal={"signal_id":"SYS-20260821-ROOM917-AUDIO-POSTRENDER-001","date":date.today().isoformat(),"project":"ROOM917","domain":"AUDIO_PRODUCTION_ENGINEERING","problem":"Accepted critical master had a durable File Library pointer but raw full-master bytes were not reacquirable (HTTP 403), while a Scene3 control WAV materialized successfully; P003A2 was therefore blocked after aggregate defect discovery.","evidence":["Full E01 master pointer/size/hash recorded in current state","Two full-master raw materialization attempts returned HTTP 403","Scene3 accepted WAV materialization succeeded, proving transport is not globally broken","Existing persistence law already requires BYTES DURABLE + READBACK ACCESS VERIFIED"],"earliest_failure_layer":"PERSISTENCE_ENFORCEMENT_AND_POST_RENDER_TOOLING","existing_rule_check":{"covered":True,"authority":"IVDIVO_NARRATIVE_OS/17_CHAT_LOCAL_ASSET_PERSISTENCE_AND_ESCROW_v1.0.md","finding":"Rule existed; enforcement/tooling and immediate byte-escrow verification were insufficient at the producing frontier."},"candidate_improvement":{"title":"Evidence-gated post-render repair compiler + executable persistence enforcement","mechanism":"Critical-master acceptance must invoke byte escrow/readback gate; post-render defects route through semantic cue lineage -> exact interval analysis -> evidence classification -> selective repair contract -> regression gate -> human listen.","candidate_type":"TOOLING_OR_AUTOMATION","scope":"GENRE_OR_DOMAIN"},"protected_invariants":["LOCKED_STORY","NO_FAKE_HUMAN_PASS","NO_BLANKET_SILENCE_FILL","SCENE3_V1_3E_LINEAGE","NO_SCALE_UNTIL_E01_V2_PROVEN"],"test":{"A":"Current document/rule-only routing","B":"Executable compiler/escrow/router/regression toolkit","acceptance":["synthetic unit tests pass","real accepted Scene3 smoke reproduces saved density facts","no patch produced from semantic-only timing","repair plan only generated for authorized classification"]},"result":"PROJECT_PILOT_PASS_FOR_TOOLING_CORE / DOMAIN_PROMOTION_HOLD_FOR_SECOND_PROJECT","decision":"ACCEPT_PROJECT_AND_HOLD_DOMAIN_PROMOTION_FOR_SECOND_PROJECT","write_through":["ROOM917 tool package","ROOM917 current engineering pointer","learning ledger observation/experiment candidate"]}
    Path(args.out).write_text(json.dumps(signal,indent=2,ensure_ascii=False)+"\n",encoding="utf-8"); print("SELF_IMPROVEMENT_SIGNAL_READY")
if __name__=="__main__": main()
